### ISSUE TITLE
Icons not loading on custom domain

### ISSUE THREAD

**Issue by theoludwig** [material-extensions/material-icons-browser-extension#108]
Hey!

I tried again (it's the 3rd time I try), to make it work with a custom domain, but it's still doesn't work. I've opened an issue, a few weeks ago, but somehow it got lost, because it was during the transition between the old and new repo (this one). 

I'm trying to make it work, for my own Gitea self-hosted instance: https://git.theoludwig.fr

The icons are not loading, and when I click on the settings icon, nothing happen.

Thank you for your help! :smile:

**Comment by theoludwig** [comment]
Any idea? @mikeydevelops 

This commit should have resolved the issue, but it's still not the case: https://github.com/material-extensions/material-icons-browser-extension/commit/0d067d039489b48993355a2362c7bd3b602467dd

**Comment by mikeydevelops** [comment]
@theoludwig It seems release on chrome web store is stuck at 1.8.15 and latest version is 1.8.18. You should check your version of the extension.

![image](https://github.com/user-attachments/assets/dc8975f0-45c1-4487-a939-fab304345f78)

I have tested with the dev version and with the latest one from the releases page, and it works with your site. If you want you can install the latest version from the zip.

**Comment by theoludwig** [comment]
Ah, you're right, the latest version published on the Chrome Web Store is v1.8.15. Do you have any idea, when new versions on GitHub will be correctly published, is opening a separated issue for that worth it?

---

> I have tested with the dev version and with the latest one from the releases page, and it works with your site. If you want you can install the latest version from the zip.

I installed from the v1.8.18 release: [github-material-icons-chrome-extension.zip](https://github.com/material-extensions/material-icons-browser-extension/releases/download/v1.8.18/github-material-icons-chrome-extension.zip) and it is indeed working, thanks! :smile:

Good workaround for the moment, but I hope, the new versions will be published soon.

**Comment by theoludwig** [comment]
Ah, never mind, another issue, for the "publish" problem has been opened, so this one can be closed.
#109

**Comment by PKief** [comment]
@theoludwig on the chrome webstore we have 1.8.19 now :)

https://chromewebstore.google.com/detail/material-icons-for-github/bggfcpfjbdkhfhfmkjpbhnkhnpjjeomc
