### ISSUE TITLE
[FEATURE_REQUEST] Registry icon for .reg files

### ISSUE THREAD

**Issue by deffcolony** [material-extensions/material-icons-browser-extension#111]
The material-icons-browser-extension is missing a icon for the .reg files 

example: https://github.com/invoke-ai/InvokeAI/tree/main/installer

The following icon svg could be used to display the .reg icon
https://commons.wikimedia.org/wiki/File:Registry.svg

![image](https://github.com/user-attachments/assets/dee5eaf3-b5fd-464e-9049-39cbf296257c)

**Comment by AdamRaichu** [comment]
Icon requests should be made in this repository, and one actually already exists! https://github.com/material-extensions/vscode-material-icon-theme/issues/1387

**Comment by deffcolony** [comment]
@AdamRaichu Thank you for pointing me in the right direction! I apologize for not checking further for existing issues before submitting this request. I appreciate the help and will check out the existing issue
