### ISSUE TITLE
Custom domains

### ISSUE THREAD

**Issue by Awokadoski** [material-extensions/material-icons-browser-extension#112]
Being able to add a custom domain, such as a domain for self-hosted GitLab or Gitea instance, would be great.

**Comment by PKief** [comment]
It should be possible already to add custom domains:

![image](https://github.com/user-attachments/assets/b48698a4-25a3-4a4f-b9a6-afd69b5d143f)

and then click again on the extension icon and click on "Add custom provider", after that it should work.

**Comment by PKief** [comment]
If it's not working please give us more information, which browser you're using.

**Comment by PKief** [comment]
Closing this issue as no further information is provided to make progress on this.

**Comment by jamiehaywood** [comment]
@PKief I would like to re-open this. It's not working for me using a custom domain BitBucket account.
