### ISSUE TITLE
[Bug] `landing` icon is missing in GitHub Repo

### ISSUE THREAD

**Issue by 1chooo** [material-extensions/material-icons-browser-extension#115]
Hi, we could find the `landing` icon in the VSCode; however, in the browser it is missing

### Screenshots

| VSCode | GitHub |
| - | - |
| <img width="1280" alt="Screenshot 2024-11-27 at 5 15 27 PM" src="https://github.com/user-attachments/assets/563615a0-d2b3-4957-933b-4f56dcea61ba"> | <img width="1280" alt="Screenshot 2024-11-27 at 5 14 51 PM" src="https://github.com/user-attachments/assets/efd4d901-61b0-4a9a-9339-090cf3abbf64"> |
 
### Info

```
Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin x64 24.0.0
```

- Material Icon Theme: `5.14.1`
- Material Icons for GitHub: `1.8.30`

**Comment by PKief** [comment]
The issue might be due to some delay in the update of the chrome extension. I just checked it again, and it's working now:

![image](https://github.com/user-attachments/assets/02253c39-593a-4238-afb9-a900894e21c9)

**Comment by 1chooo** [comment]
Hey @PKief It work successfully, thanks for your kind work!
