### ISSUE TITLE
Symlink icons are not preserved

### ISSUE THREAD

**Issue by kidonng** [material-extensions/material-icons-browser-extension#75]
This has been fixed in #3, but is now a regression.

Example: https://github.com/lxqt/lxqt

Native:

<img width="193" alt="image" src="https://github.com/Claudiohbsantos/github-material-icons-extension/assets/44045911/a8637b30-27d5-48d2-9f5b-11b243efa10c">

With extension:

<img width="193" alt="image" src="https://github.com/Claudiohbsantos/github-material-icons-extension/assets/44045911/a6dda546-70f4-4b99-b76a-0de6605e54b9">

**Comment by csandman** [comment]
Weird, for me (on v1.8.6) they all appear to be working for me:

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/9214195/01fe3b8a-6cb6-4c42-8326-9de3cba2721c)

**Comment by kidonng** [comment]
Thanks for reminding me having some preview features enabled (this issue particularly could be due to "New Repository Overview").

I will check again with them disabled later.

**Comment by csandman** [comment]
Ah, yes I gave it a shot with that preview flag and have the same issue. Oh, and these are submodules btw.

Tbh, with that feature preview, there really isn't a good way to determine if a folder is a submodule anymore. The only distinguishing feature I can find on the icons is the SVG's actual path. Other than that, the `aria-label` attributes the icons had before are no longer included. It's probably worth waiting until this feature is made non-experimental before anything is done to try and fix it.
