### ISSUE TITLE
Icons not being applied on GitLab

### ISSUE THREAD

**Issue by justbispo** [material-extensions/material-icons-browser-extension#76]
On GitLab, only the default icons are being shown.
But the correct icon is still being shown in the README title bellow the list of files.

![2023-11-15 01 04 40 gitlab com](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/38961424/aaafb4d7-50fb-4da4-96d0-136b274ff8c1)

**Comment by mikeydevelops** [comment]
This was fixed in #85, the pull request was merged in the new fork and then the fork was merged back here. You can close this issue now.
