### ISSUE TITLE
Extension stopped working on Azure DevOps

### ISSUE THREAD

**Issue by SaifAqqad** [material-extensions/material-icons-browser-extension#82]
It seems Azure DevOps has changed the css classes/layout used for the icons

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/47293197/79058ed2-a87d-4a42-b3cf-ea1fa7343d52)

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/47293197/32235973-727e-4b69-acd0-4d57845b4fc5)

**Comment by mikeydevelops** [comment]
This is fixed in #85, it was closed here but was merged in the new fork, and now that fork is merged back here. You can close this issue now.

**Comment by PKief** [comment]
As #85 has been merged with https://github.com/material-extensions/material-icons-browser-extension/commit/0d067d039489b48993355a2362c7bd3b602467dd I'm going to close this issue now.
