### ISSUE TITLE
Could you add a GUI/UI folder icon

### ISSUE THREAD

**Issue by DanielDekhtyar** [material-extensions/material-icons-browser-extension#83]
Could you add an icon for a UI/ GUI folder?
Thanks!

**Comment by AdamRaichu** [comment]
Icon requests should be directed to [this repo](https://github.com/PKief/vscode-material-icon-theme/issues/new?assignees=&labels=&projects=&template=icon_request.md&title=%5BIcon+Request%5D+%3Cicon_name%3E).

**Comment by PKief** [comment]
Has been added with PR https://github.com/material-extensions/vscode-material-icon-theme/pull/2382. It will be part of the next update 😊
