### ISSUE TITLE
Icons Not Displayed for Specific Angular File Types

### ISSUE THREAD

**Issue by Abodawoud** [material-extensions/material-icons-browser-extension#87]
## **Icons are not being displayed for certain Angular TypeScript files, specifically those with the extensions:**

- ### **`*.component.ts`**
-  ### **`*.guard.ts`**
- ### **`*.service.ts`**

### **Steps to Reproduce**

1. Open any Angular TypeScript file with the above extensions in the project.
2. Observe the absence of the expected icons.

### **Expected Behavior**
Icons should be displayed for .component.ts, .service.ts, and .guard.ts files in Angular projects.

### **Actual Behavior**

Icons are missing for these specific file types, as illustrated in the image below.

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/109487123/20b51f81-0ea5-4376-a4f6-dfcad7c5a38c)

Thank you for looking into this issue and for your effort!🤗

**Comment by PKief** [comment]
This is related to https://github.com/Claudiohbsantos/github-material-icons-extension/issues/86
