### ISSUE TITLE
With a large amount of files, icons torwards the end will not load

### ISSUE THREAD

**Issue by SomeAspy** [material-extensions/material-icons-browser-extension#91]
inherited from upstream: https://github.com/Claudiohbsantos/github-material-icons-extension/issues/80

Thanks for taking up development on this extension!

**Comment by PKief** [comment]
@SomeAspy I just transfered your issue into the upstream again. We were able to move the upstream repository into the new organization, so everthing can be continued to be maintained here. 

Feel free to close #80 and continue discussing in this one - or the other way round - whatever you prefer is the best ;)

**Comment by PKief** [comment]
Completed with #103
