### ISSUE TITLE
Folder Icons Not Shown When Used as Submodules

### ISSUE THREAD

**Issue by fawzibazari** [material-extensions/material-icons-browser-extension#92]
Here is an example:

![Capture d’écran 2024-07-04 à 11 14 01](https://github.com/material-extensions/material-icons-browser-extension/assets/67472505/d3cc089f-0191-41aa-bc9b-86b628f176d8)

It should have this icon:

![Capture d’écran 2024-07-04 à 11 14 36](https://github.com/material-extensions/material-icons-browser-extension/assets/67472505/42dc8383-ed53-4df3-8aaf-0b50985b0e37)

Thanks in advance !

**Comment by fawzibazari** [comment]
Hello @mikeydevelops,

Is it normal for the `protos` folder to have the default icon instead of the `proto` folder icon ?

Thanks !

**Comment by mikeydevelops** [comment]
No, it appears, the latest version 1.8.16 is not published on chrome store.

Here is a snapshot of it working:
![image](https://github.com/user-attachments/assets/65d129d2-55be-4a2f-9fc5-71d4fb936c65)

You have to just wait for the release to publish, probably sometime in the following days.
