### ISSUE TITLE
Custom domains not working on chromium browsers

### ISSUE THREAD

**Issue by justbispo** [material-extensions/material-icons-browser-extension#96]
After the last update I've tried the new function implemented in #85. It seems it works on Firefox but not on chromium browsers.

On Firefox, it correctly shows the popup to configure the provider:
![codeberg firefox 1](https://github.com/material-extensions/material-icons-browser-extension/assets/38961424/7e9dc42b-ee1d-468d-84f7-49a7a1251b5a)
And then the icons change and the I can configure the icon style:
![codeberg firefox 2](https://github.com/material-extensions/material-icons-browser-extension/assets/38961424/cf071ffd-de8a-43f7-924f-002946d69844)

But on chromium browsers, it shows the popup to allow access to the website:
![codeberg chromium 1](https://github.com/material-extensions/material-icons-browser-extension/assets/38961424/0be3c1b0-06f2-4ade-ab6f-b5ef41e6c483)
Then the popup content doesn't change. I have to click away of the popup and open it again. But the provider configuration doesn't show up:
![codeberg chromium 2](https://github.com/material-extensions/material-icons-browser-extension/assets/38961424/e61a7830-4568-428f-adc0-5fc1a07b7ed9)

**Comment by mikeydevelops** [comment]
There was, some miscommunication and appears that a required permission was removed from the extension manifest. This is a quick fix and it should be working in the next release.
